version: '3.8'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  en2ar-service:
    build: ./EN2AR-Service
    ports:
      - "8000:8000"
    depends_on:
      - redis
  ar2en-service:
    build: ./AR2EN-Service
    ports:
      - "5000:5000"
    depends_on:
      - redis
